<?php

declare(strict_types=1);

namespace Pota\Adif\Tests\Fixtures;

/**
 * Shared test data generators for ADIF tests.
 */
final class AdifFixtures
{
    /**
     * Returns a valid entry with all required fields.
     */
    public static function validEntry(array $overrides = []): array
    {
        $base = [
            'band' => '20M',
            'call' => 'K1ABC',
            'mode' => 'SSB',
            'operator' => 'W1AW',
            'qso_date' => '20231225',
            'time_on' => '1234',
            'pota_my_park_ref' => 'US-0001',
        ];

        return array_merge($base, $overrides);
    }

    /**
     * Returns a valid ADIF string with minimal content.
     */
    public static function validAdifString(): string
    {
        return "Generated by test\n<eoh>\n" .
               "<band:3>20M<call:5>K1ABC<mode:3>SSB<operator:4>W1AW" .
               "<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>";
    }

    /**
     * Returns an invalid ADIF string without proper markers.
     */
    public static function invalidAdifString(): string
    {
        return "No valid ADIF markers here";
    }

    /**
     * Generates a multi-entry ADIF string.
     */
    public static function multiEntryAdifString(int $count = 5): string
    {
        $entries = [];
        for ($i = 0; $i < $count; $i++) {
            $call = sprintf('K%dABC', $i);
            $time = sprintf('%04d', 1200 + ($i * 5));
            $entries[] = sprintf(
                "<band:3>20M<call:%d>%s<mode:3>SSB<operator:4>W1AW" .
                "<qso_date:8>20231225<time_on:4>%s<pota_my_park_ref:7>US-0001<eor>",
                strlen($call),
                $call,
                $time
            );
        }
        return "Test\n<eoh>\n" . implode("\n", $entries);
    }

    /**
     * Returns an ADIF string with duplicate entries.
     */
    public static function duplicateAdifString(): string
    {
        $entry = "<band:3>20M<call:5>K1ABC<mode:3>SSB<operator:4>W1AW" .
                 "<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>";
        return "Test\n<eoh>\n" . $entry . "\n" . $entry . "\n" . $entry;
    }

    /**
     * Returns an ADIF string with POTA FER (multiple parks) entries.
     */
    public static function potaFerAdifString(): string
    {
        return "Test\n<eoh>\n" .
               "<band:3>20M<call:5>K1ABC<mode:3>SSB<operator:4>W1AW" .
               "<qso_date:8>20231225<time_on:4>1234" .
               "<my_pota_ref:15>US-0001,US-0002<pota_ref:15>CA-0001,CA-0002<eor>";
    }

    /**
     * Returns an ADIF string with location suffixes.
     */
    public static function potaWithLocationAdifString(): string
    {
        return "Test\n<eoh>\n" .
               "<band:3>20M<call:5>K1ABC<mode:3>SSB<operator:4>W1AW" .
               "<qso_date:8>20231225<time_on:4>1234" .
               "<my_pota_ref:10>US-0001@WA<pota_ref:10>CA-0001@ON<eor>";
    }

    /**
     * Returns sample headers for testing.
     */
    public static function sampleHeaders(): array
    {
        return [
            'programid' => 'TestApp',
            'programversion' => '1.0.0',
            'adif_version' => '3.1.4',
        ];
    }

    /**
     * Generates an ADIF string with specified entry count for performance testing.
     */
    public static function largeAdifString(int $entryCount): string
    {
        $entries = [];
        for ($i = 0; $i < $entryCount; $i++) {
            $call = sprintf('K%05dA', $i);
            $hour = 12 + intval($i / 3600);
            $min = intval(($i % 3600) / 60);
            $sec = $i % 60;
            $time = sprintf('%02d%02d%02d', $hour % 24, $min, $sec);

            $entries[] = sprintf(
                "<band:3>20M<call:%d>%s<mode:3>SSB<operator:4>W1AW" .
                "<qso_date:8>20231225<time_on:6>%s<pota_my_park_ref:7>US-0001<eor>",
                strlen($call),
                $call,
                $time
            );
        }
        return "Performance test\n<eoh>\n" . implode("\n", $entries);
    }
}
