<?php

declare(strict_types=1);

namespace Pota\Adif\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Pota\Adif\Document;
use Pota\Adif\Linter;

final class LinterTest extends TestCase
{
    public function test_accepts_valid_basic_adif_format(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<band:3>20M<mode:3>SSB<eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function test_rejects_adif_without_eoh(): void
    {
        $text = '<call:5>W1AW<band:3>20M<mode:3>SSB<eor>';

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
        $this->assertEquals(Linter::$BAD_FORM['@'], $result['@']);
    }

    public function test_rejects_adif_without_eor(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<band:3>20M<mode:3>SSB";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
    }

    public function test_rejects_empty_adif(): void
    {
        $text = '';

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
    }

    public function test_default_mode_does_not_check_required_fields(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function test_pota_mode_checks_required_fields(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<eor>";

        $result = Linter::lint($text, Document::MODE_POTA);
        $this->assertNotEmpty($result);
        $this->assertArrayHasKey(0, $result);

        // Should contain missing required fields
        $missing = $result[0];
        $this->assertContains('band', $missing);
        $this->assertContains('mode', $missing);
        $this->assertContains('operator', $missing);
        $this->assertContains('qso_date', $missing);
        $this->assertContains('time_on', $missing);
        $this->assertContains('pota_my_park_ref', $missing);
    }

    public function test_pota_mode_accepts_complete_entry(): void
    {
        $text = "Generated by test\n<eoh>\n" .
                '<band:3>20M<call:5>W1AW<mode:3>SSB<operator:4>W1AW' .
                '<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>';

        $result = Linter::lint($text, Document::MODE_POTA);
        $this->assertEmpty($result);
    }

    public function test_lint_pota_fails_on_empty_record(): void
    {
        $text = '<eor>';

        $result = Linter::lintPota($text);
        $this->assertEquals(Linter::$BAD_FORM, $result);
    }

    public function test_pota_mode_checks_multiple_entries(): void
    {
        $text = "Generated by test\n<eoh>\n" .
                '<band:3>20M<call:5>W1AW<mode:3>SSB<operator:4>W1AW' .
                "<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>\n" .
                "<call:5>K1ABC<eor>\n" .
                '<band:3>40M<call:5>N1XYZ<mode:2>CW<operator:4>W1AW' .
                '<qso_date:8>20231225<time_on:4>1300<pota_my_park_ref:7>US-0002<eor>';

        $result = Linter::lint($text, Document::MODE_POTA);

        // First entry (index 0) should be OK
        $this->assertArrayNotHasKey(0, $result);

        // Second entry (index 1) should have errors
        $this->assertArrayHasKey(1, $result);
        $this->assertContains('band', $result[1]);

        // Third entry (index 2) should be OK
        $this->assertArrayNotHasKey(2, $result);
    }

    public function test_pota_mode_checks_multiple_entries_without_bootstrap(): void
    {
        $text = "Generated by test\n<eoh>\n" .
                '<band:3>20M<call:5>W1AW<mode:3>SSB<operator:4>W1AW' .
                "<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>\n" .
                "<call:5>K1ABC<eor>\n" .
                '<band:3>40M<call:5>N1XYZ<mode:2>CW<operator:4>W1AW' .
                '<qso_date:8>20231225<time_on:4>1300<pota_my_park_ref:7>US-0002<eor>';

        $result = Linter::lintPota(trim($text));

        // First entry (index 0) should be OK
        $this->assertArrayNotHasKey(0, $result);

        // Second entry (index 1) should have errors
        $this->assertArrayHasKey(1, $result);
        $this->assertContains('band', $result[1]);

        // Third entry (index 2) should be OK
        $this->assertArrayNotHasKey(2, $result);
    }

    public function test_handles_case_insensitive_eoh_eor(): void
    {
        $text = "Generated by test\n<EOH>\n<call:5>W1AW<band:3>20M<mode:3>SSB<EOR>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function test_handles_mixed_case_eoh_eor(): void
    {
        $text = "Generated by test\n<Eoh>\n<call:5>W1AW<band:3>20M<mode:3>SSB<Eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function test_handles_whitespace(): void
    {
        $text = "  \n  Generated by test  \n  <eoh>  \n  <call:5>W1AW<eor>  \n  ";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function test_handles_multiple_eor_in_default_mode(): void
    {
        $text = "Test\n<eoh>\n<call:5>W1AW<eor>\n<call:5>K1ABC<eor>\n<call:5>N1XYZ<eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function test_rejects_only_whitespace(): void
    {
        $text = "   \n\n   \t   ";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
    }

    public function test_accepts_minimal_valid_adif(): void
    {
        $text = '<eoh><eor>';

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function test_pota_mode_returns_array_of_errors_per_entry(): void
    {
        $text = "Test\n<eoh>\n<call:5>W1AW<eor>\n<call:5>K1ABC<eor>";

        $result = Linter::lint($text, Document::MODE_POTA);

        // Both entries should have errors (missing required fields)
        $this->assertArrayHasKey(0, $result);
        $this->assertArrayHasKey(1, $result);
        $this->assertIsArray($result[0]);
        $this->assertIsArray($result[1]);
    }
}
