<?php

declare(strict_types=1);

namespace Pota\Adif\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Pota\Adif\Linter;
use Pota\Adif\Document;

final class LinterTest extends TestCase
{
    public function testAcceptsValidBasicAdifFormat(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<band:3>20M<mode:3>SSB<eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function testRejectsAdifWithoutEoh(): void
    {
        $text = "<call:5>W1AW<band:3>20M<mode:3>SSB<eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
        $this->assertEquals('ADIF requires <eoh> and at least one <eor>', $result['@']);
    }

    public function testRejectsAdifWithoutEor(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<band:3>20M<mode:3>SSB";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
    }

    public function testRejectsEmptyAdif(): void
    {
        $text = "";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
    }

    public function testDefaultModeDoesNotCheckRequiredFields(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function testPotaModeChecksRequiredFields(): void
    {
        $text = "Generated by test\n<eoh>\n<call:5>W1AW<eor>";

        $result = Linter::lint($text, Document::MODE_POTA);
        $this->assertNotEmpty($result);
        $this->assertArrayHasKey(0, $result);

        // Should contain missing required fields
        $missing = $result[0];
        $this->assertContains('band', $missing);
        $this->assertContains('mode', $missing);
        $this->assertContains('operator', $missing);
        $this->assertContains('qso_date', $missing);
        $this->assertContains('time_on', $missing);
        $this->assertContains('pota_my_park_ref', $missing);
    }

    public function testPotaModeAcceptsCompleteEntry(): void
    {
        $text = "Generated by test\n<eoh>\n" .
                "<band:3>20M<call:5>W1AW<mode:3>SSB<operator:4>W1AW" .
                "<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>";

        $result = Linter::lint($text, Document::MODE_POTA);
        $this->assertEmpty($result);
    }

    public function testLintPotaFailsOnEmptyRecord(): void
    {
        $text = "<eor>";

        $result = Linter::lintPota($text);
        $this->assertEquals(Linter::$BAD_FORM, $result);
    }

    public function testPotaModeChecksMultipleEntries(): void
    {
        $text = "Generated by test\n<eoh>\n" .
                "<band:3>20M<call:5>W1AW<mode:3>SSB<operator:4>W1AW" .
                "<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>\n" .
                "<call:5>K1ABC<eor>\n" .
                "<band:3>40M<call:5>N1XYZ<mode:2>CW<operator:4>W1AW" .
                "<qso_date:8>20231225<time_on:4>1300<pota_my_park_ref:7>US-0002<eor>";

        $result = Linter::lint($text, Document::MODE_POTA);

        // First entry (index 0) should be OK
        $this->assertArrayNotHasKey(0, $result);

        // Second entry (index 1) should have errors
        $this->assertArrayHasKey(1, $result);
        $this->assertContains('band', $result[1]);

        // Third entry (index 2) should be OK
        $this->assertArrayNotHasKey(2, $result);
    }

    public function testPotaModeChecksMultipleEntriesWithoutBootstrap(): void
    {
        $text = "Generated by test\n<eoh>\n" .
                "<band:3>20M<call:5>W1AW<mode:3>SSB<operator:4>W1AW" .
                "<qso_date:8>20231225<time_on:4>1234<pota_my_park_ref:7>US-0001<eor>\n" .
                "<call:5>K1ABC<eor>\n" .
                "<band:3>40M<call:5>N1XYZ<mode:2>CW<operator:4>W1AW" .
                "<qso_date:8>20231225<time_on:4>1300<pota_my_park_ref:7>US-0002<eor>";

        $result = Linter::lintPota(trim($text));

        // First entry (index 0) should be OK
        $this->assertArrayNotHasKey(0, $result);

        // Second entry (index 1) should have errors
        $this->assertArrayHasKey(1, $result);
        $this->assertContains('band', $result[1]);

        // Third entry (index 2) should be OK
        $this->assertArrayNotHasKey(2, $result);
    }

    public function testHandlesCaseInsensitiveEohEor(): void
    {
        $text = "Generated by test\n<EOH>\n<call:5>W1AW<band:3>20M<mode:3>SSB<EOR>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function testHandlesMixedCaseEohEor(): void
    {
        $text = "Generated by test\n<Eoh>\n<call:5>W1AW<band:3>20M<mode:3>SSB<Eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function testHandlesWhitespace(): void
    {
        $text = "  \n  Generated by test  \n  <eoh>  \n  <call:5>W1AW<eor>  \n  ";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function testHandlesMultipleEorInDefaultMode(): void
    {
        $text = "Test\n<eoh>\n<call:5>W1AW<eor>\n<call:5>K1ABC<eor>\n<call:5>N1XYZ<eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function testRejectsOnlyWhitespace(): void
    {
        $text = "   \n\n   \t   ";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertArrayHasKey('@', $result);
    }

    public function testAcceptsMinimalValidAdif(): void
    {
        $text = "<eoh><eor>";

        $result = Linter::lint($text, Document::MODE_DEFAULT);
        $this->assertEmpty($result);
    }

    public function testPotaModeReturnsArrayOfErrorsPerEntry(): void
    {
        $text = "Test\n<eoh>\n<call:5>W1AW<eor>\n<call:5>K1ABC<eor>";

        $result = Linter::lint($text, Document::MODE_POTA);

        // Both entries should have errors (missing required fields)
        $this->assertArrayHasKey(0, $result);
        $this->assertArrayHasKey(1, $result);
        $this->assertIsArray($result[0]);
        $this->assertIsArray($result[1]);
    }
}
